CI: Build check with various optimization levels
The submodules are built locally, which may lead to build failures.
Specifically, the dtc submodule fails to build when using GCC versions
11.4.0 or 12.3.0 with optimization levels set to -O0 or with debug flag
-g. This is a critical issue, as it can disable the debug mode. To
address this, optimization levels and debug level build are introduced
to stabilize the pull request changes.

The compiled error:
/usr/bin/ld: /tmp/cc2eaHdM.ltrans0.ltrans.o: in function fdt_del_node':
<artificial>:(.text+0x279f0): undefined reference to fdt_node_end_offset_'
collect2: error: ld returned 1 exit status

Note: I have only used gcc 11.4.0 and gcc 12.3.0 to test this out.
Github runners should test other compilers.

After bisecting, the original cause was found after #534.