Fix compiler error when enabling JIT
When using make 'ENABLE_JIT=1', the following error is observed:

src/jit.c:1760:17: error: ‘do_sret’ defined but not used [-Werror=unused-function]
 1760 |     static void do_##inst(struct jit_state *state UNUSED, riscv_t *rv UNUSED, \
      |                 ^~~

Add "SYSTEM" to the EXT_LIST, which cause SERT to be add SKIP_LIST
during template generation. The prevents the generatoin of unused JIT
code for the SERT instruction.

Fixes: fc0d878 ("Preliminary support for trap handling during block emulation")