Fix compiler errors with JIT when Zbc is disabled
When using 'make ENABLE_Zbc=0 ENABLE_JIT=1', the following errors are
observed:

src/jit.c:1760:17: error: ‘do_clmulr’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_clmulh’ defined but not used [-Werror=unused-function]
src/jit.c:1760:17: error: ‘do_clmul’ defined but not used [-Werror=unused-function]

Include 'Zbc' in EXT_LIST to ensure instructions like 'clmulr',
'clmulh', and 'clmul' are properly handled, resolving unused function
errors during JIT builds.